name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
    tags:
    - '**'
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.x
    - name: Ensure generated code is committed
      run: make generate manifests && git diff --exit-code
    - name: Test
      run: make test
    - name: Get version from tags
      id: version
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: Publish
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
        AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        make publish
    - name: Publish Tag
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
        AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
        RELEASE_TAG: v${{ steps.version.outputs.tag }}
      run: |
        make publish-tag
