name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
    tags:
    - '**'
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.16.x
    - name: Ensure generated code is committed
      run: make generate manifests && git diff --exit-code
    - name: Test
      run: make test
    - name: Get version from tags
      id: version
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/')
      env:
        KO_DOCKER_REPO: ghcr.io/${{ github.repository_owner }}
        AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
        VERSION: ${{ steps.version.outputs.tag }}
      run: |
        echo "${AUTH_TOKEN}" | docker login ghcr.io --username ${REPOSITORY_OWNER} --password-stdin
        make publish
    - name: Update the release with Kubernetes resources
      uses: softprops/action-gh-release@v0.1.12
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release.yaml
